"use client";

import type { Metadata } from "next";
import GlobalStyles from "@/styles/global";
import theme from "@/styles/theme";
import { ThemeProvider } from "styled-components";
import Header from "@/components/layout/Header";

const metadata: Metadata = {
  title: "Travel Space",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ThemeProvider theme={theme}>
      <GlobalStyles />
      <html>
        <body>
          <Header />
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
