import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Travel Space Post",
  description: "Generated by create next app",
};

export default function Post() {
  return (
    <>
      <div>postpostpost</div>
    </>
  );
}
